# Generated by Django 5.1.2 on 2024-10-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('director', models.CharField(blank=True, default='', max_length=100)),
                ('rating', models.FloatField()),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
    ]
