# Generated by Django 5.1.3 on 2024-11-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
    ]
