# Generated by Django 5.1.3 on 2024-11-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster_path',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
