# Generated by Django 5.1.3 on 2024-11-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movies_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='movies',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='year',
        ),
        migrations.AddField(
            model_name='movies',
            name='popularity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='release_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='movies',
            name='vote_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
