# Generated by Django 5.1.3 on 2024-12-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movies_options_remove_movies_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(default='1994-09-23'),
        ),
    ]
